[project]
name = 'Decentralized-Cross-Industry-Innovation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collaboration]
path = 'contracts/collaboration.clar'
clarity_version = 2
epoch = 2.5

[contracts.innovation-registry]
path = 'contracts/innovation-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.innovator-verification]
path = 'contracts/innovator-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
